### ISSUE TITLE
Can we use it without context ?

### ISSUE THREAD

**Issue by dhsont** [DokkarRachidReda/Fancy-Flutter-Alert-Dialog#3]
HI i want to display alert box from my service class where context is not present,
can you make it to work without context ?

It will be good feature.

**Comment by DokkarRachidReda** [comment]
Hello, thanks for using my package. 
I made some quick researchs and I think that it's not possible to show any kind of alert dialogs without context, however I suggest to show the alert in the widget that uses your service(throw an exception in case your are looking to show an error dialog, or try to check the return value of your service), another suggestion is to pass the context with the constructor but I think it won't work
Good luck 🤞

**Comment by dhsont** [comment]
Thanks for quick reply,
i saw toast packages https://pub.dev/packages/overlay_support
it is wrapping material app as child and you can call showToast() without context.
~~~
OKToast(
  /// set toast style, optional
  child:MaterialApp()
);
~~~

you can call anywhere 
~~~
showToast("Hello");
~~~
so i thought it could be possible to this package also. 


Though i have achieved this through this tutorial

 https://www.filledstacks.com/post/manager-your-flutter-dialogs-with-a-dialog-manager

But builtin feature will be good.

**Comment by DokkarRachidReda** [comment]
Thanks for that helpful answer
I will try to implement this feature using the first suggestion, it looks easy to implement.
